// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
//
// 【本地修改 2026-10-07】按用户要求去掉密码功能：已删除全部 5 处
// `rest.WithJwt(serverCtx.Config.Auth.AccessSecret)`，即所有 /api/* 都不再校验 JWT。
// 保留 /api/auth（前端仍会调它拿 token，但拿不到也能用）。
// ⚠️ 安全影响：任何能访问该端口的人都能控制 Docker。仅用于内网实例。

package handler

import (
	"net/http"

	auth "github.com/onlyLTY/dockerCopilot/internal/handler/auth"
	container "github.com/onlyLTY/dockerCopilot/internal/handler/container"
	icons "github.com/onlyLTY/dockerCopilot/internal/handler/icons"
	image "github.com/onlyLTY/dockerCopilot/internal/handler/image"
	progress "github.com/onlyLTY/dockerCopilot/internal/handler/progress"
	version "github.com/onlyLTY/dockerCopilot/internal/handler/version"
	"github.com/onlyLTY/dockerCopilot/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: webindexHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth",
				Handler: auth.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/rename",
				Handler: container.RenameHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/restart",
				Handler: container.RestartHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/start",
				Handler: container.StartHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/stop",
				Handler: container.StopHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/update",
				Handler: container.UpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/container/backup",
				Handler: container.BackupHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/container/backup2compose",
				Handler: container.Backup2composeHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/container/backups",
				Handler: container.DelRestoreHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/backups/restore",
				Handler: container.RestoreHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/container/listBackups",
				Handler: container.ListBackupsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/containers",
				Handler: container.ContainersListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: icons.UploadHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: icons.ObtainHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/icons"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodDelete,
				Path:    "/image/:id",
				Handler: image.RemoveHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/images",
				Handler: image.ImagesListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/progress/:taskid",
				Handler: progress.GetProgressHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPut,
				Path:    "/program",
				Handler: version.UpdateProgramHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/version",
				Handler: version.VersionHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)
}
